// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"` // parameters are auto validated
}

type Response struct {
	Message string `json:"message"`
}

type User struct {
	Id              uint   `json:"id"`
	Uid             uint   `json:"uid"`
	Username        string `json:"username"`
	Gender          int    `json:"gender"`
	Email           string `json:"email"`
	Role            string `json:"role"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRes struct {
	UserId  int   `json:"userId"`
	Token string `json:"token"`
}

type RegisterReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Tel       int    `json:"tel"`
}

type UserInfoRes struct {
	UserInfo      User          `json:"user_info"`
}


type UserInfoReq struct {
	Username  string `json:"username"`
	Uid uint32 `json:"uid"`
}
